"""edit fied required

Revision ID: 04b2c93cb105
Revises: 9e7c42e0e492
Create Date: 2024-06-15 16:22:01.383502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '04b2c93cb105'
down_revision = '9e7c42e0e492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral', 'Source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('Source', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
