"""Add source link to user

Revision ID: 399c60ab29a9
Revises: 25220aaf861f
Create Date: 2024-06-20 11:45:49.758014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '399c60ab29a9'
down_revision = '25220aaf861f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('assigned_source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'source', ['assigned_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'assigned_source_id')
    # ### end Alembic commands ###
