"""edit fied required

Revision ID: 42f6267745a7
Revises: dca0af20b4db
Create Date: 2024-06-15 16:48:00.869159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42f6267745a7'
down_revision = 'dca0af20b4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
