"""added rate override

Revision ID: 55e3e7adc035
Revises: d38c7fb805e3
Create Date: 2024-06-27 13:24:18.205019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55e3e7adc035'
down_revision = 'd38c7fb805e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
