"""FirstGeneration

Revision ID: 58941c804338
Revises: e2412789c190
Create Date: 2024-06-07 14:33:13.583333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '58941c804338'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'source', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.alter_column('source', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
