"""added rate override

Revision ID: 62dc04418112
Revises: b1e076cbef1e
Create Date: 2024-06-27 13:16:18.197731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '62dc04418112'
down_revision = 'b1e076cbef1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
