"""Add source to referral public

Revision ID: 823daaece31a
Revises: e616a4c1ee36
Create Date: 2024-06-20 12:50:33.922379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '823daaece31a'
down_revision = 'e616a4c1ee36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
