"""Cleaning some class

Revision ID: 8fe419a7050f
Revises: aa346315f015
Create Date: 2024-06-26 15:30:36.822955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fe419a7050f'
down_revision = 'aa346315f015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circs_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circs_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('referral_allocation', 'Source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_allocation', sa.Column('Source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('claim', 'client_lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circs_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circs_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
