"""Add supplier model datetime

Revision ID: 92f735e5195d
Revises: 5d2e76ef2101
Create Date: 2024-06-11 15:18:23.333538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92f735e5195d'
down_revision = '5d2e76ef2101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('supplier', sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_column('supplier', 'modified_on')
    op.drop_column('supplier', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('supplier', sa.Column('modified_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('supplier', 'updated_datetime')
    op.drop_column('supplier', 'created_datetime')
    # ### end Alembic commands ###
