"""edit fied required

Revision ID: 9e7c42e0e492
Revises: f549d3ffdff7
Create Date: 2024-06-14 13:47:01.072962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e7c42e0e492'
down_revision = 'f549d3ffdff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authority', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circs_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circs_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_address_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_address_town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_vehicle_reg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_insurer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_insurer_policyno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'client_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'accident_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('claim', 'accident_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('claim', 'accident_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'accident_circs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_address_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_address_town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_vehicle_reg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_insurer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_insurer_polcyno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'tp_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral_allocation', 'sentdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('referral_allocation', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral_allocation', 'responsedate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('source_rate', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_rate', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_rate', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('source_rate', 'hire_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_rate', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier_rate', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier_rate', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('supplier_rate', 'hire_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('veh_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('veh_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('veh_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('veh_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier_rate', 'hire_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_rate', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('supplier_rate', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier_rate', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_rate', 'hire_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('source_rate', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('source_rate', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_rate', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referral_allocation', 'responsedate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('referral_allocation', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referral_allocation', 'sentdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('referral', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_insurer_polcyno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_insurer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_vehicle_reg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_address_town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_address_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'tp_firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'accident_circs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'accident_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'accident_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('claim', 'accident_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('claim', 'plate_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_insurer_policyno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_insurer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_vehicle_reg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_address_town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_address_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'client_firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circs_group', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circs_group', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authority', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
