"""Add constraint to supplier_rate

Revision ID: 9edf47558091
Revises: f9729800dad4
Create Date: 2024-06-25 21:12:45.431082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9edf47558091'
down_revision = 'f9729800dad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Supplier_Rate_Constraint', 'supplier_rate', type_='unique')
    op.create_unique_constraint('supplier_rate_constraint', 'supplier_rate', ['authority_id', 'veh_group_id', 'circs_group_id', 'supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('supplier_rate_constraint', 'supplier_rate', type_='unique')
    op.create_unique_constraint('Supplier_Rate_Constraint', 'supplier_rate', ['authority_id', 'veh_group_id', 'circs_group_id', 'supplier_id'])
    # ### end Alembic commands ###
