"""set req for base_rate

Revision ID: a1563c57883e
Revises: f3759d1ee4b6
Create Date: 2024-06-26 09:04:39.712329

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1563c57883e'
down_revision = 'f3759d1ee4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
