"""Add column to referral

Revision ID: a603d214d406
Revises: cb8e1a8be864
Create Date: 2024-06-24 21:27:07.533077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a603d214d406'
down_revision = 'cb8e1a8be864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('authority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'referral', 'authority', ['authority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.drop_column('referral', 'authority_id')
    # ### end Alembic commands ###
