"""Add total column to supplier_stats

Revision ID: a646d1eab4ab
Revises: a603d214d406
Create Date: 2024-06-25 11:40:29.655376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a646d1eab4ab'
down_revision = 'a603d214d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_stat', sa.Column('total_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_stat', 'total_rank')
    # ### end Alembic commands ###
