"""added fields to referral table

Revision ID: b1e076cbef1e
Revises: f8b89cc1b8b2
Create Date: 2024-06-27 12:19:03.791433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1e076cbef1e'
down_revision = 'f8b89cc1b8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('circs_group_id', sa.Integer(), nullable=True))
    op.add_column('referral', sa.Column('veh_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'referral', 'veh_group', ['veh_group_id'], ['id'])
    op.create_foreign_key(None, 'referral', 'circs_group', ['circs_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.drop_column('referral', 'veh_group_id')
    op.drop_column('referral', 'circs_group_id')
    # ### end Alembic commands ###
