"""Add columns to suplier stats

Revision ID: cb8e1a8be864
Revises: 42a2dea4a6ed
Create Date: 2024-06-24 21:11:46.543196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb8e1a8be864'
down_revision = '42a2dea4a6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_stat', sa.Column('uniquecol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'supplier_stat', ['uniquecol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_stat', type_='unique')
    op.drop_column('supplier_stat', 'uniquecol')
    # ### end Alembic commands ###
