"""added rate override

Revision ID: d38c7fb805e3
Revises: 62dc04418112
Create Date: 2024-06-27 13:21:31.934219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd38c7fb805e3'
down_revision = '62dc04418112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_rate', 'rate_override',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_rate', 'rate_override',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
