"""Cleaning some class

Revision ID: d9a45d01d476
Revises: 8fe419a7050f
Create Date: 2024-06-26 15:37:37.038724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9a45d01d476'
down_revision = '8fe419a7050f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
