"""edit fied required

Revision ID: dca0af20b4db
Revises: 04b2c93cb105
Create Date: 2024-06-15 16:27:22.125845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dca0af20b4db'
down_revision = '04b2c93cb105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
