"""Add source to referral public

Revision ID: e616a4c1ee36
Revises: 399c60ab29a9
Create Date: 2024-06-20 11:58:22.227750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e616a4c1ee36'
down_revision = '399c60ab29a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
