"""Add supplier_stats

Revision ID: f327615111b1
Revises: bb189524fc88
Create Date: 2024-06-24 15:25:43.111509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f327615111b1'
down_revision = 'bb189524fc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_stat', 'authority_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_stat', 'veh_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_stat', 'circs_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_stat', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('supplier_stat', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_stat', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_stat', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_stat', 'circs_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_stat', 'veh_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier_stat', 'authority_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
