"""Add base rate to supplier

Revision ID: f3759d1ee4b6
Revises: 9edf47558091
Create Date: 2024-06-25 21:55:44.547783

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3759d1ee4b6'
down_revision = '9edf47558091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('base_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'base_rate')
    # ### end Alembic commands ###
