"""edit fied required

Revision ID: f549d3ffdff7
Revises: 547b8cc58ce0
Create Date: 2024-06-14 13:39:33.653054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f549d3ffdff7'
down_revision = '547b8cc58ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authority', 'created_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('supplier', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'address_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'address_town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'Tel',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier', 'Tel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('supplier', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier', 'address_postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier', 'address_town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier', 'address_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplier', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authority', 'created_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
