"""added field for override

Revision ID: f8b89cc1b8b2
Revises: d9a45d01d476
Create Date: 2024-06-27 11:29:58.929192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8b89cc1b8b2'
down_revision = 'd9a45d01d476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authority', 'created_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('supplier_rate', sa.Column('rate_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_rate', 'rate_override')
    op.alter_column('authority', 'created_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
