"""Add constraint to supplier_rate

Revision ID: f9729800dad4
Revises: a646d1eab4ab
Create Date: 2024-06-25 20:40:48.882094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f9729800dad4'
down_revision = 'a646d1eab4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Supplier_Rate_Constraint', 'supplier_rate', ['authority_id', 'veh_group_id', 'circs_group_id', 'supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Supplier_Rate_Constraint', 'supplier_rate', type_='unique')
    # ### end Alembic commands ###
